# CheckMates Digest - wird von einrichten.sh in die nginx-Sites eingebunden
location /checkmates {
	auth_basic           "checkmates";
	auth_basic_user_file /etc/nginx/.htpasswd;
	try_files $uri $uri/ $uri.html =404;
}
